# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImagePack',
        ),
        migrations.AddField(
            model_name='pack',
            name='normatif',
            field=models.CharField(choices=[('NR', 'N.R'), ('ECO', 'écolo')], default=(0, 'N.R.'), max_length=255, verbose_name='Critère normatif'),
        ),
        migrations.AlterField(
            model_name='famillepack',
            name='slug',
            field=models.CharField(max_length=4, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='slug',
            field=models.CharField(default='00', max_length=255, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='sousfamillepack',
            name='slug',
            field=models.CharField(max_length=6, unique=True, verbose_name='Référence'),
        ),
    ]
