# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import materiaux.models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legende', models.CharField(default='', max_length=255, verbose_name='Légende')),
                ('imagefile', models.ImageField(blank=True, upload_to=materiaux.models.image_file_name, verbose_name='Image')),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaux.Materiau', verbose_name='Matériau associé')),
            ],
        ),
    ]
