# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiau',
            name='reference',
        ),
        migrations.AddField(
            model_name='materiau',
            name='slug',
            field=models.CharField(default='00', max_length=255, unique=True, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='materiau',
            name='normatif',
            field=models.CharField(choices=[('NR', 'N.R'), ('ECO', 'écolo')], default=(0, 'N.R.'), max_length=255, verbose_name='Critère normatif'),
        ),
    ]
