# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0002_auto_20170310_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiau',
            name='prorietes',
            field=models.TextField(default=None, null=True, verbose_name='Propriétés'),
        ),
        migrations.AddField(
            model_name='materiau',
            name='qrcode',
            field=models.ImageField(default=None, null=True, upload_to='materiauxpyth'),
        ),
    ]
