# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0003_auto_20170315_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiau',
            name='prorietes',
        ),
        migrations.AddField(
            model_name='materiau',
            name='proprietes',
            field=models.TextField(default='{}', null=True, verbose_name='Propriétés'),
        ),
    ]
